// Spec 3.4 and 10.2: all 28 questions and 56 answers, in characters and pinyin.
// They are written to docs/reviews/golden-strings.md, which the Mandarin reviewer
// signs off; any change to a string fails this test until the file is updated
// (pnpm vitest -u) and reviewed again.
import { describe, expect, test } from "vitest";
import { content } from "../content/index.ts";
import hsk1 from "../content/hsk1.json";
import { allQuestions } from "./questions.ts";
import { renderAnswer, renderQuestion, tokensText } from "./render.ts";

const prons = ["pr.ta.m", "pr.ta.f"];
const rows = allQuestions(content).flatMap((q) =>
  prons.map((p) => ({
    q: renderQuestion(content, p, q.verbId, q.nounId),
    yes: renderAnswer(content, p, q.verbId, q.nounId, true),
    no: renderAnswer(content, p, q.verbId, q.nounId, false),
  })),
);
const han = (s: string) => [...s.matchAll(/\p{Script=Han}/gu)].map((m) => m[0]);

test("28 questions and 56 answers", () => {
  expect(rows).toHaveLength(28);
  expect(new Set(rows.map((r) => r.q.hanzi)).size).toBe(28);
  expect(new Set(rows.flatMap((r) => [r.yes.hanzi, r.no.hanzi])).size).toBe(56);
});

test("the golden strings file matches", async () => {
  const table = rows
    .map((r) => [r.q, r.yes, r.no].map((s) => `${s.hanzi}<br>${s.pinyin}`).join(" | "))
    .map((cells) => `| ${cells} |`);
  const file = [
    "# Golden strings (spec 3.4)",
    "",
    "Generated by `src/languages/zh/engine/golden.test.ts`. Every question and answer the game can show. The Mandarin reviewer signs off this file (spec 10.1); the test fails if a string changes.",
    "",
    "| Question | Yes | No |",
    "|---|---|---|",
    ...table,
    "",
  ].join("\n");
  await expect(file).toMatchFileSnapshot("../../../../docs/reviews/golden-strings.md");
});

describe("the spec's examples", () => {
  test.each([
    ["pr.ta.m", "v.you", "n.gou", "他有狗吗？", "Tā yǒu gǒu ma?"],
    ["pr.ta.f", "v.shi", "n.yisheng", "她是医生吗？", "Tā shì yīshēng ma?"],
    ["pr.ta.m", "v.zai", "n.xuexiao", "他在学校吗？", "Tā zài xuéxiào ma?"],
    ["pr.ta.m", "v.shi", "n.nande", "他是男的吗？", "Tā shì nán de ma?"],
  ])("%s %s %s", (p, v, n, hanzi, pinyin) => {
    expect(renderQuestion(content, p, v, n)).toMatchObject({ hanzi, pinyin });
  });

  test.each([
    ["pr.ta.m", "v.you", "n.gou", false, "没有，他没有狗。", "Méiyǒu, tā méiyǒu gǒu."],
    ["pr.ta.f", "v.zai", "n.xuexiao", true, "在，她在学校。", "Zài, tā zài xuéxiào."],
    ["pr.ta.m", "v.shi", "n.yisheng", false, "不是，他不是医生。", "Bú shì, tā bú shì yīshēng."],
    ["pr.ta.f", "v.zai", "n.jia", false, "不在，她不在家。", "Bú zài, tā bú zài jiā."],
    ["pr.ta.m", "v.you", "n.shouji", true, "有，他有手机。", "Yǒu, tā yǒu shǒujī."],
  ] as const)("%s %s %s %s", (p, v, n, truth, hanzi, pinyin) => {
    expect(renderAnswer(content, p, v, n, truth)).toMatchObject({ hanzi, pinyin });
  });

  test("segments carry the lexicon id of each word, and none for punctuation", () => {
    expect(renderQuestion(content, "pr.ta.m", "v.you", "n.gou").segments).toEqual([
      { hanzi: "他", pinyin: "tā", lexiconId: "pr.ta.m" },
      { hanzi: "有", pinyin: "yǒu", lexiconId: "v.you" },
      { hanzi: "狗", pinyin: "gǒu", lexiconId: "n.gou" },
      { hanzi: "吗", pinyin: "ma", lexiconId: "pt.ma" },
      { hanzi: "？", pinyin: "?" },
    ]);
  });

  test("tokens as text have no punctuation", () => {
    expect(tokensText(content, ["pr.ta.m", "n.gou", "v.you", "pt.ma"])).toBe("他狗有吗");
  });
});

describe.each(rows.map((r) => [r.q.hanzi, r] as const))("%s", (_, r) => {
  test("answers contain the asker's pronoun and never the other (D6)", () => {
    const [mine, other] = r.q.hanzi.startsWith("他") ? ["他", "她"] : ["她", "他"];
    for (const a of [r.yes, r.no]) {
      expect(a.hanzi).toContain(mine);
      expect(a.hanzi).not.toContain(other);
    }
  });

  test("every character is in an HSK 1 headword (spec 3.3)", () => {
    const chars = new Set(hsk1.words.flatMap(han));
    for (const s of [r.q, r.yes, r.no])
      for (const c of han(s.hanzi)) expect(chars.has(c), c).toBe(true);
  });

  test("full-width punctuation, no spaces in characters; capitalised pinyin", () => {
    for (const s of [r.q, r.yes, r.no]) {
      expect(s.hanzi).not.toMatch(/[\s?,.]/);
      expect(s.pinyin).toMatch(/^\p{Lu}/u);
      expect(s.pinyin).not.toMatch(/[\d，。？]|\s[,.?]|\s{2}/);
    }
  });

  test("no answer uses 不有", () => {
    for (const a of [r.yes, r.no]) expect(a.hanzi).not.toContain("不有");
  });
});
